### PR TITLE
Fixed random failure in commit creation

### LINKED ISSUE #8: Random failure in commit creation
```json
{
  "status": 201,
  "url": "https://api.github.com/repos/bigbinary/neeto-compliance/git/refs",
  "headers": {
    "access-control-allow-origin": "*",
    "access-control-expose-headers": "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset",
    "cache-control": "private, max-age=60, s-maxage=60",
    "connection": "close",
    "content-length": "399",
    "content-security-policy": "default-src 'none'",
    "content-type": "application/json; charset=utf-8",
    "date": "Thu, 07 Sep 2023 06:53:32 GMT",
    "etag": "\"90846467562dc852b1e459932c482ea59e5b6c349c417e349131e089a758a863\"",
    "location": "https://api.github.com/repos/bigbinary/neeto-compliance/git/refs/heads/bump-gem-version",
    "referrer-policy": "origin-when-cross-origin, strict-origin-when-cross-origin",
    "server": "GitHub.com",
    "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
    "vary": "Accept, Authorization, Cookie, X-GitHub-OTP, Accept-Encoding, Accept, X-Requested-With",
    "x-accepted-github-permissions": "contents=write; contents=write,workflows=write",
    "x-content-type-options": "nosniff",
    "x-frame-options": "deny",
    "x-github-api-version-selected": "2022-11-28",
    "x-github-media-type": "github.v3; format=json",
    "x-github-request-id": "33C1:5F4D:EDEBF8:1E4AA27:64F9736C",
    "x-ratelimit-limit": "1000",
    "x-ratelimit-remaining": "998",
    "x-ratelimit-reset": "1694073212",
    "x-ratelimit-resource": "core",
    "x-ratelimit-used": "2",
    "x-xss-protection": "0"
  },
  "data": {
    "ref": "refs/heads/bump-gem-version",
    "node_id": "MDM6UmVmNDA1ODQ5NTkxOnJlZnMvaGVhZHMvYnVtcC1nZW0tdmVyc2lvbg==",
    "url": "https://api.github.com/repos/bigbinary/neeto-compliance/git/refs/heads/bump-gem-version",
    "object": {
      "sha": "46c967d6d27d3cb5dc81f82dd69e3e5b7ff2368f",
      "type": "commit",
      "url": "https://api.github.com/repos/bigbinary/neeto-compliance/git/commits/46c967d6d27d3cb5dc81f82dd69e3e5b7ff2368f"
    }
  }
}
```

Ref: https://github.com/bigbinary/neeto-compliance/actions/runs/6093972228/job/16534580128

### PR DESCRIPTION
**Pull request by Thejus-Paul**
- Fixes #8

### CODE REVIEW

**Comment by Thejus-Paul** [comment]
@rishadp2747 _a Please verify.

**Comment by rishadp2747** [comment]
@Thejus-Paul _a Sometimes it's failing. Can we retry the failed request 2 or 3 times?

Few failing cases: 
- https://rishad-p.neetorecord.com/watch/f0673d5b-c629-4210-ac44-49821a5f5489
- https://rishad-p.neetorecord.com/watch/48488d50-a345-4c3c-a846-cedfc9dad78f

**Comment by Thejus-Paul** [comment]
@rishadp2747 _a I have tested in my personal repo as well as in your personal repo. I have moved the branch creation logic to the commit creation script and then added the logic to retry the script 5 times with a 5-second delay between each try. This script is resilient enough in my opinion. We need to remove `continue-on-error: true` from the `bump-version.yml` file in neetoCommonsBackend so that it becomes apparent in case it fails. 



Once this PR gets merged, we can make the necessary changes in neetoCommonsBackend and verify its effectiveness in tomorrow's compliance release. In the meantime, I'll work on raising a [PR for mono-repos](https://github.com/bigbinary/bump-product-version/pull/12) and create a separate release.

cc: @chiraggshah

**Review by rishadp2747 — APPROVED** [review]
@Thejus-Paul LGTM

@chiraggshah _a. Please review and merge

**Review by chiraggshah — APPROVED** [review]

**Pull request merged**
